FLAGS=CC=i586-mingw32msvc-g++ LD=i586-mingw32msvc-g++ LDFLAGS=-lws2_32 NAME=tcptunnel.exe

all:
	cd src; make $(FLAGS)

install:
	cd src; make $(FLAGS) install

uninstall:
	cd src; make $(FLAGS) uninstall

clean:
	cd src; make $(FLAGS) clean

